version: '3.8'

services:
  lecture-notes-app:
    build: .
    container_name: lecture-notes-app
    ports:
      - "8501:8501"
    volumes:
      - ./.env:/app/.env
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
